site_name: Hebrew Documentation
site_description: A python package with methods to handle the complexities of Hebrew text, calculate Gematria, and more.
site_url: https://hebrew.aviperl.me/
repo_name: avi-perl/Hebrew
repo_url: https://github.com/avi-perl/Hebrew

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      watch:
        - hebrew/

extra_css:
- css/style.css
- css/material.css
- css/mkdocstrings.css

markdown_extensions:
  - mdx_include
  - toc:
      permalink: "×œ"  # Heh


extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/__aviperl__
    - icon: fontawesome/brands/github
      link: https://github.com/avi-perl
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/avrohomperl/