site_name: Hebrew Documentation
site_description: A python package with methods to handle the complexities of Hebrew text.
site_url: https://avi-perl.github.io/Hebrew/
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
repo_name: avi-perl/Hebrew
repo_url: https://github.com/avi-perl/Hebrew
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - mdx_include
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/__aviperl__
    - icon: fontawesome/brands/github
      link: https://github.com/avi-perl
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/avrohomperl/